# Generated by Django 5.0.3 on 2024-03-20 13:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BRAND',
            fields=[
                ('brand_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CATEGORIES',
            fields=[
                ('categories_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categories', models.CharField(max_length=20)),
                ('categories_image', models.ImageField(default='', upload_to='categories-images')),
            ],
        ),
        migrations.CreateModel(
            name='COLOUR',
            fields=[
                ('colour_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('colour_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ADDRESS',
            fields=[
                ('address_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FEATURED_PRODUCT',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('gender', models.CharField(choices=[('Woman', 'Woman'), ('Man', 'Man')], max_length=10)),
                ('product_image', models.ImageField(upload_to='products')),
                ('product_desc', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.brand')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.categories')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.colour')),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCT',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('gender', models.CharField(choices=[('Woman', 'Woman'), ('Man', 'Man')], max_length=10)),
                ('product_image', models.ImageField(upload_to='products')),
                ('product_desc', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.brand')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.categories')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.colour')),
            ],
        ),
        migrations.CreateModel(
            name='ORDER',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Delivered', 'Delivered'), ('Out For Delivery', 'Out For Delivery'), ('Shipped', 'Shipped'), ('Order Confirmed', 'Order Confirmed'), ('Cancle', 'Cancle')], default='pending', max_length=50)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.product')),
            ],
        ),
        migrations.CreateModel(
            name='CART',
            fields=[
                ('cart_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.product')),
            ],
        ),
        migrations.CreateModel(
            name='WISHLIST',
            fields=[
                ('wishlist_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
